name: 'Deploy an OpenAI Model to Azure action'
description: 'This action helps create an OpenAI search model'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to log in to azure'
    required: true
  tenant-id:
    description: 'Tenant id to log in to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  location:
    description: 'Location to deploy OpenAI resource to'
    required: true
  applicationPassword:
    description: 'Client secret for app'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3

    - name: 'az cli login'
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true

    - name: 'Install azd'
      uses: Azure/setup-azd@v0.1.0

    - name: 'Install Nodejs'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Create directory'
      run: mkdir airepo
      shell: pwsh

    - name: 'Change directory'
      run: cd airepo
      shell: pwsh

    - name: 'List directories'
      run: dir
      shell: pwsh

    - name: 'Log in with Azure (Federated Credentials)'
      run: |
        azd auth login `
          --client-id ${{ inputs.client-id }} `
          --federated-credential-provider "github" `
          --tenant-id ${{ inputs.tenant-id }}
      shell: pwsh

    - name: 'Update bot_config.yaml'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'AOAISearchDemo/app/backend/bot_config.yaml'
        commitChange: false
        changes: |
          {
            "approach_classifier.openai_settings.engine": "chat",
            "structured_query_nl_to_sql.openai_settings.engine": "chat",
            "structured_query_nl_to_sql.model_params.model_name": "gpt-35-turbo",
            "structured_final_answer_generation.openai_settings.engine": "chat",
            "unstructured_search_query_generation.openai_settings.engine": "chat",
            "unstructured_final_answer_generation.openai_settings.engine": "chat",
            "unstructured_final_answer_generation.model_params.model_name": "gpt-35-turbo",
            "embeddings.openai_settings.engine": "embedding"
          }

    - name: 'Update azure.yaml to skip Connect-AzAccount step'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'AOAISearchDemo/azure.yaml'
        commitChange: false
        changes: |
          {
            "hooks.preprovision.run": "Install-Module AzureAD -Force;Get-AzContext;$principalId = (Get-AzADUser -UserPrincipalName (Get-AzContext).Account).Id;azd env set AZURE_PRINCIPAL_ID $principalId"
          }

    - name: Install Azure PowerShell module
      shell: pwsh
      run: |
        # Check if the Az module is present, if not, install it
        if (-not (Get-Module -ListAvailable -Name Az)) {
          Install-Module -Name Az.Accounts -Scope CurrentUser -Force -AllowClobber
          Install-Module -Name Az.ManagedServiceIdentity -Scope CurrentUser -Force -AllowClobber
        }
      working-directory: AOAISearchDemo
      
    - name: Az powershell
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Update-AzConfig -DefaultSubscriptionForLogin ${{ inputs.subscription-id }}
          $identity = Get-AzUserAssignedIdentity -ResourceGroupName rg-new7 -Name vsk-github-UAMI
          Connect-AzAccount -Identity -AccountId $identity.ClientId # Run on the virtual machine
        azPSVersion: "latest"

    - name: 'Log in with Azure (Federated Credentials)'
      run: |
        azd up --no-prompt -e new7
      shell: pwsh
      working-directory: AOAISearchDemo
      env: 
        ENV_NAME: "new7"
        AZURE_LOCATION: "eastus"
        AZURE_OPENAI_LOCATION: "eastus"
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
