name: 'Deploy an OpenAI Model to Azure action'
description: 'This action helps create an OpenAI search model'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to log in to azure'
    required: true
  tenant-id:
    description: 'Tenant id to log in to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  location:
    description: 'Location to deploy OpenAI resource to'
    required: true
  principal-id:
    description: 'FIC Service Principal ID'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3

    - name: 'az cli login'
      uses: azure/login@v2.1.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true

    - name: 'Install azd'
      uses: Azure/setup-azd@v0.1.0

    - name: 'Install Nodejs'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Create directory'
      run: mkdir airepo
      shell: pwsh

    - name: 'Change directory'
      run: cd airepo
      shell: pwsh

    - name: 'List directories'
      run: dir
      shell: pwsh

    - name: 'Log in with Azure (Federated Credentials)'
      run: |
        azd auth login `
          --client-id ${{ inputs.client-id }} `
          --federated-credential-provider "github" `
          --tenant-id ${{ inputs.tenant-id }}
      shell: pwsh

    - name: 'Update bot_config.yaml'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'AOAISearchDemo/app/backend/bot_config.yaml'
        commitChange: false
        changes: |
          {
            "approach_classifier.openai_settings.engine": "gpt-35-turbo",
            "structured_query_nl_to_sql.openai_settings.engine": "gpt-35-turbo",
            "structured_query_nl_to_sql.model_params.model_name": "gpt-35-turbo",
            "structured_final_answer_generation.openai_settings.engine": "gpt-35-turbo",
            "unstructured_search_query_generation.openai_settings.engine": "gpt-35-turbo",
            "unstructured_final_answer_generation.openai_settings.engine": "gpt-35-turbo",
            "unstructured_final_answer_generation.model_params.model_name": "gpt-35-turbo",
            "embeddings.openai_settings.engine": "text-embedding-ada-002"
          }

    - name: 'Update azure.yaml to skip Connect-AzAccount step'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'AOAISearchDemo/azure.yaml'
        commitChange: false
        changes: |
          {
            "hooks.preprovision.run": "Install-Module AzureAD -Force;Get-AzContext; azd env set AZURE_PRINCIPAL_ID 4d94dbeb-4a0b-441f-b183-aa77361917fe"
          }

    - name: Install ODBC Driver for SQL Server v18
      uses: Yarden-zamir/install-mssql-odbc@v1.0.2

    
    - name: Az powershell
      uses: azure/powershell@v2
      with:
        inlineScript: |
          cd AOAISearchDemo
          Install-Module -Name Az -Force -RequiredVersion 11.5.0
          $PSVersionTable
          azd env new new17
          azd env set AZURE_ENV_NAME "new17"
          azd env set AZURE_LOCATION "southcentralus"
          azd env set AZURE_OPENAI_LOCATION "southcentralus"
          azd env set AZURE_SUBSCRIPTION_ID ${{ inputs.subscription-id }}
          azd env set AZURE_PRINCIPAL_ID ${{ inputs.principal-id }}
          Get-AzContext -ListAvailable
          azd up --no-prompt -e new17
        azPSVersion: "9.2"
